apiVersion: v1
kind: Namespace
metadata:
  name: swing-trader
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-data-pvc
  namespace: swing-trader
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
